# Generated by Django 6.0 on 2025-12-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sarees', 'Sarees'), ('dress', 'Dresses'), ('offers', 'Offers')], max_length=50),
        ),
    ]
