# Generated by Django 5.2.4 on 2025-10-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
