# Generated by Django 6.0 on 2026-01-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_mrp_alter_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sarees', 'Sarees'), ('dresses', 'Dresses'), ('offers', 'Offers')], max_length=50),
        ),
    ]
