# Generated by Django 6.0 on 2026-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sarees', 'Sarees'), ('dress', 'Dresses'), ('offers', 'Offers')], max_length=50),
        ),
    ]
