# Generated by Django 6.0 on 2026-01-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
